export const TRANSLATE_TEXT = "TRANSLATE_TEXT";
export const TRANSLATE_TEXT_SUCCESS = "TRANSLATE_TEXT_SUCCESS";
export const TRANSLATE_TEXT_ERROR = "TRANSLATE_TEXT_ERROR";

export const GET_LANGUAGES = "GET_LANGUAGES";
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS";
export const GET_LANGUAGES_ERROR = "GET_LANGUAGES_ERROR";

export const DETECT_LANGUAGE = "DETECT_LANGUAGE";
export const DETECT_LANGUAGE_SUCCESS = "DETECT_LANGUAGE_SUCCESS";
export const DETECT_LANGUAGE_ERROR = "DETECT_LANGUAGE_ERROR";

export const ADD_TRANSLATION_TO_HISTORY = "ADD_TRANSLATION_TO_HISTORY";
export const CLEAR_TRANSLATION_HISTORY = "CLEAR_TRANSLATION_HISTORY";

export const ADD_TRANSLATION_TO_FAVORITES = "ADD_TRANSLATION_TO_FAVORITES";
export const REMOVE_TRANSLATION_FROM_FAVORITES = "REMOVE_TRANSLATION_FROM_FAVORITES";


